title: Reja Gunner's Blog
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://zigic88.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: zigic88
   twitter: brianmaierjr
   facebook: zigic.gunz
   email: shin_hye@rocketmail.com

google_analytics: "UA-58263416-1"
